In [118]:
# import all dependencies and data
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt
import seaborn as sns
import calendar
from sklearn import neural_network

import utils

%matplotlib notebook
pd.set_option('chained_assignment',None)
sns.set_style("white")

data = pd.read_csv('claims.csv')
#cleaning temporal data
data = utils.clean_data(data)

In [119]:
counted = data.groupby(["FraudFound_P"]).size()

In [120]:
#features to categorize
features = ["Make","WeekOfMonth", "WeekOfMonthClaimed", "Month", "DayOfWeek", 
            "AccidentArea", "DayOfWeekClaimed", "MonthClaimed", "Sex", "MaritalStatus", 
            "Age", "Fault", "PolicyType", "VehicleCategory", "VehiclePrice", 
            "DriverRating", "PastNumberOfClaims", 
            "AgeOfVehicle", "AgeOfPolicyHolder", "PoliceReportFiled", "WitnessPresent", 
            "AgentType", "NumberOfSuppliments", "AddressChange_Claim", "NumberOfCars", 
            "Year", "BasePolicy"]

In [121]:
Ydata = data["FraudFound_P"]
data = data[features]
for i in features:
    data[i] = data[i].astype('category')

In [122]:
#Dummies and to numpy array
Xdata = pd.get_dummies(data).as_matrix()
Ydata = Ydata.as_matrix()

In [129]:
clf2 = neural_network.MLPClassifier(hidden_layer_sizes= (50,20,4))

In [130]:
clf2.fit(Xdata, Ydata)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(50, 20, 4), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [136]:
np.sum(Ydata != clf2.predict(Xdata))

86

In [142]:
ydatadf = pd.DataFrame(Ydata)

TypeError: __init__() got an unexpected keyword argument 'label'

In [137]:
condition = pd.DataFrame(Ydata != clf2.predict(Xdata))

In [143]:
final  = pd.concat([ydatadf, condition], axis =  1)
final.columns = ['Ydata', 'condition']

In [146]:
final[final['condition'] ==  True]

       Ydata  condition
107        1       True
128        0       True
360        1       True
512        1       True
543        1       True
686        0       True
789        1       True
1037       1       True
1174       1       True
1391       1       True
1392       0       True
1855       1       True
1902       0       True
1918       0       True
2178       0       True
2299       1       True
2320       0       True
2821       1       True
3022       0       True
3223       1       True
3371       0       True
3534       1       True
3892       0       True
3936       1       True
4055       0       True
4275       0       True
4595       1       True
4672       1       True
5082       0       True
5213       0       True
...      ...        ...
9758       1       True
9877       0       True
9971       1       True
9985       0       True
10134      1       True
10411      0       True
10704      0       True
10886      1       True
11014      0       True
11313      0       True
11534      0       True
11565      0       True
12158      0       True
12324      0       True
12386      0       True
12551      0       True
12803      0       True
12911      0       True
13248      0       True
13251      0       True
13274      1       True
13297      1       True
13911      0       True
14110      0       True
14301      0       True
14374      1       True
14420      0       True
14813      1       True
14955      1       True
15033      0       True

[86 rows x 2 columns]